### ISSUE TITLE
http request error

### ISSUE THREAD

**Issue by alexandre-rassinoux** [skyscrapr/terraform-provider-cloudability#12] opened 2020-07-16 10:00 UTC
Hello,

Thank you for this provider, but when I work with many cloudability accounts, most of the time it produces an error during plan or apply: 

https://api.cloudability.com/v3/vendors/aws/accounts/XXXXXX: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Thank you in advance for your help,

**Comment by skyscrapr** [comment] 2020-07-16 10:06
That looks like an http client config issue. Let me take a look. I’ll try to update later today

**Comment by skyscrapr** [comment] 2020-07-16 10:41
Sorry it isn’t that easy to know how to fix this. 
Can you please submit a log using TF_LOG or detail the steps to reproduce. Thanks

**Comment by alexandre-rassinoux** [comment] 2020-07-16 11:43
Thank you for your help.
I retried to launch a plan, and everything goes well.

I think it is more a problem on Cloudability API side (sometimes the api reject some of the requests...)

If the problem occurs again, I will inform you.

**Comment by skyscrapr** [comment] 2020-07-17 06:37
Great news. Ok. I’ll close the issue. But if I’m being honest I’m using a guess for the http client timeouts so there could be some tweaking needed there. I have not done any scale testing. Please re-open if needed.

**Closed by skyscrapr** 2020-07-17 06:37 UTC
